### ISSUE TITLE
Definición del proyecto:

### ISSUE THREAD

**Issue by Ucamo** [TonyMtz/project-x#1]
Hay que definir los siguientes puntos:

-Que género de juego vamos a hacer? (Plataforma?)
-2D o 3D?
-Cuál es el alcance del proyecto? (Entre mas chico mejor, para ir probando)
-¿Que engine usaremos? (Unity como habíamos dicho?)
-En que plataforma se publicará?

En lo personal, un plataformer en 2D con Unity considero estaría bien, pero igual estoy abierto a otras posibilidades, no tengo problema por ninguno de los puntos, hay que discutirlos.

Te anexo la lista de assets que tengo comprado en el Asset store de Unity.

https://www.assetstore.unity3d.com/en/#!/content/4010
https://www.assetstore.unity3d.com/en/#!/content/4274
https://www.assetstore.unity3d.com/en/#!/content/10172
https://www.assetstore.unity3d.com/en/#!/content/11786 (hechale un ojo)
https://www.assetstore.unity3d.com/en/#!/content/368 (a este también)

dejo tambièn un link a juegos de Unity que he hecho.
http://gamejolt.com/profile/uriel-carrillo/328047/games

y este que hicimos para un GGJ, carlos, josepe, harry y yo http://trochi-mochi.com/QiS/QuesitoIsSuffering.html

**Comment by tonymtz** [comment]
Si es plataforma, todo bien. Soy fan de los 2D asi que tiene mi voto.

Alcance: por discutir

Engine: Unity

Plataforma: Lancemos un juego para android. Podemos usar tu plugin para hacerlo 2.5D, aunque en lo personal me gustaria hacerlo desde cero para aprender bien que rollo.

Se me antoja algo como este: https://www.youtube.com/watch?v=_gn6PC9G9L0

Juegos que he hecho:

https://play.google.com/store/apps/details?id=com.gamesrum.guesstheword
https://play.google.com/store/apps/details?id=com.gamesrum.amazeing (este actualmente esta offline, necesito cambiar mi hosting)
https://play.google.com/store/apps/details?id=com.informalpenguins.rocketprincess
http://www.kongregate.com/games/tonymx/olo

Y actualmente trabajando en StarDog (primer juego que hago con unity), lo liberare cuando un compa que esta trabajando en los assets termine xD

**Comment by Ucamo** [comment]
Muy bien, yo estoy trabajando actualmente en un Infinite Runner, pero no tengo problema con hacer este proyecto también en Paralelo.

Las gráficas buscamos que sean 2.5D o 2D.

Con Pixel art o modelos 3D y vista 2.5D?

**Comment by tonymtz** [comment]
Te dejo que tu elijas eso jajaja. No tengo ni idea de como hacer modelos 3D ni animarlos. No se cuanta cantidad de trabajo sera eso.

Si la idea es sacar un juego rapido, creo que pixel art es la mejor opcion. Igual y mas adelante podemos "relanzar" el juego, con algun par de dinamicas agregadas y modelos 3D :P

**Comment by Ucamo** [comment]
Ok, que sea Pixel art.

Entonces tenemos:

Un juego 2D con Pixel art, Plataforma en Unity, que sea como el que pasaste, importaremos para Android.

Ok, me pondré a bajar el Unity para ir teniendo algo sobre lo que trabajar.

El Alcance del juego es lo que tenemos que definir, pero yo creo que lo veríamos cuando tengamos la funcionabilidad.

Tema cerrado.

**Comment by tonymtz** [comment]
Te agregue a un nuevo board de Trello para ir organizando el desarrollo
