### ISSUE TITLE
Game Name

### ISSUE THREAD

**Issue by Ucamo** [TonyMtz/project-x#11]
What is the name of the game?

I would like it to had the name Laika on it.

Suggestions:

A combination of:

1)
-"The Adventures of "
-"The Journey of "

2)
-Laika

3)
-"The Space Dog"
-"Saves the World"
-"The Cosmonaut"
-"Mission: Armaggedon"
-"Mission: Apocalypse"
-"The Earth Defender"
-"The Earth Guardian"

1)+2)+3)
or
2)+3)

Example:
-"The Adventures of Laika The Space Dog"
-"Laika The Earth Guardian"

It could have commas and such, what do you think? @tonymtz

**Comment by tonymtz** [comment]
Laika: The Journey :D

**Comment by Ucamo** [comment]
Please make a list of possible names so we can choose one :P

**Comment by tonymtz** [comment]
It's hard... I'm creating a list of keywords better:
- space
- laser
- dog
- lost
- jumping
- spaceship
- corgi
- foreign
- mars
- pluto

**Comment by Ucamo** [comment]
Laika The Space Dog?

**Comment by tonymtz** [comment]
I'd like to play with the idea of several subtitles just in case we get an another idea, I'd put a colon after the dog's name:

```
Laika: The Space Dog
```

I can see the same format for future titles:

```
Laika: Reloaded
Laika: The Crossover
```

I don't know, something like that lol

**Comment by Ucamo** [comment]
What if we call it "Laika", and made a list of name's combination and each time the title screen shows up, a combination of the subtitle show up, in the same way as minecraft shows subtitles on the login screen.

![minecraft](http://ubuntuhandbook.org/wp-content/uploads/2013/11/minecraft-game.jpg)

The yellow words are pulled from a random list.

something like that?

maybe we can do something like, when the player finish the game, it reads a really meaningful title for Laika.

**Comment by tonymtz** [comment]
this is not what I had in mind 😛 

I prefer to stick with `laika the space dog`.

**Comment by Ucamo** [comment]
Laika the space dog it is.
