### ISSUE TITLE
Links útiles.

### ISSUE THREAD

**Issue by Ucamo** [TonyMtz/project-x#2]
Aquí vamos poniendo los links a revisar que nos parezcan útiles para el desarrollo.

Tiled, Creación de mapas en tilesets.
http://www.mapeditor.org/
Plugin para importar a Unity esos mapas
http://www.seanba.com/tiled2unity
Overlap2D, Editor de niveles independiente del engine
http://overlap2d.com/

Aseprite, editor de pixel art.
http://www.aseprite.org/
Spriter, editor de animaciónes
https://brashmonkey.com/
Graphicsgale, Editor pixel art
https://graphicsgale.com/us/index.html

**Comment by tonymtz** [comment]
Tengo el spriter pro en mi steam, por si lo ocupas ahi esta.

**Comment by Ucamo** [comment]
También tengo el Spriter Pro en Steam.

PlaceHolder art:
http://kenney.nl/assets/platformer-pack-redux

Tutorial 2D plataformer:
https://unity3d.com/es/learn/tutorials/topics/2d-game-creation

Otro tutorial 2D, pero para un Roguelike
https://unity3d.com/es/learn/tutorials/projects/2d-roguelike-tutorial

**Comment by tonymtz** [comment]
Sprites que podemos agarrar como base:
https://finalbossblues.itch.io/pixel-shooter-towers-asset-pack (enemies cutes)
https://thkaspar.itch.io/micro-character-bases (moar enemies)
https://finalbossblues.itch.io/pixel-platformer-pack (basic world)
https://tadeuszsynzygmunta.itch.io/pixel-gui-pack (gui)

Inspiracion:

![https://img.itch.io/aW1hZ2UvNDYxNjUvMjUzNDAyLmdpZg==/original/8aqQo9.gif](https://img.itch.io/aW1hZ2UvNDYxNjUvMjUzNDAyLmdpZg==/original/8aqQo9.gif)
