### ISSUE TITLE
Movimiento del personaje necesita mejoras.

### ISSUE THREAD

**Issue by Ucamo** [TonyMtz/project-x#3]
El movimiento de "Player" no se siente bien, es como si patinara mucho, hay que ver que podemos hacer para corregirlo.

¿Vamos a programar todo en javascript o en C#?, por mi no hay problema en cualquiera, pero hay que elegir uno para llevar un estándar.

**Comment by tonymtz** [comment]
C#

**Comment by Ucamo** [comment]
perfecto, ya estoy trabajando checa el nuevo branch, ahi hice otro controlador en c#, falta ponerle el salto y los controllers de la física.

**Comment by tonymtz** [comment]
Arreglado
